# Generated by Django 4.1.3 on 2023-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
